### PR TITLE
Add some more flexible usage

### PR DESCRIPTION
**Pull request by shanzi**
using `BB_WWW_PLUGINS` instead of `BB_WWW` so that we can set and install needed plugins.
using `BB_CHECKOUT` to set the branch or tag to checkout.

There is a little problem on heroku that install and compiling the `base` or `md_base` plugin is too slow, considering adding support for pre-compiled pack.

compiling `base` or `md_base` on dokku is fast. maybe it is the limit of CPU or storage of heroku caused the slow of building.

### CODE REVIEW

**Comment by tardyp** [comment]
Do you know that wheels of the packages are available there:
ftp://ftp.buildbot.net/pub/latest/

I think this is a better option than trying to rebuild everything each time

matabuildbot is building those, you can make a pr to enable autogeneration of base-md:
https://github.com/buildbot/metabbotcfg/blob/master/builders.py

**Comment by tardyp** [comment]
Also, I think an easier option to install buildbot deps is to use the standard requirements.txt.

Here is how I did it for buildbot_travis:
https://github.com/tardyp/buildbot_travis_bin

With this method, it is not necessary to maintain a special buildpack, the application is just a plain python app.

**Comment by shanzi** [comment]
@tardyp I use this buildpack to deploy live demo, so sometimes install from git repo may be necessary.

For common users installing from wheels is a better choice. I will add the support in the future.

**Comment by tardyp** [comment]
yes, of course. You could also give an option to give the wheel as part of the app. (that's what I did for bb travis)

**Pull request merged**
